"""Miniature IOI S2 setting implementation."""

from .data import S2DatasetBundle, build_s2_dataset_bundle, generate_training_latents, split_manifest_records
from .model import (
    CANONICAL_TEMPLATE,
    CONTEXT_LENGTH,
    D_MLP,
    D_MODEL,
    FAMILY_CANONICAL,
    FAMILY_SHIFT,
    INTERVENTION_VARS,
    NAME_VOCAB,
    N_HEADS,
    N_LAYERS,
    OTHER_TOKEN,
    SHIFT_TEMPLATE,
    MiniIOILatents,
    MiniIOIRun,
    MiniIOITokenizer,
    MiniIOITransformer,
)
from .nulls import (
    NullSpec,
    build_shuffled_pair_dataset_bundle,
    run_candidate_like_null_search,
    run_random_site_null_search,
    shuffled_pair_is_available,
)
from .scoring import MiniIOICandidateSearchEngine, SearchSpec, candidate_table_rows

__all__ = [
    "CANONICAL_TEMPLATE",
    "CONTEXT_LENGTH",
    "D_MLP",
    "D_MODEL",
    "FAMILY_CANONICAL",
    "FAMILY_SHIFT",
    "INTERVENTION_VARS",
    "MiniIOICandidateSearchEngine",
    "MiniIOILatents",
    "MiniIOIRun",
    "MiniIOITokenizer",
    "MiniIOITransformer",
    "NAME_VOCAB",
    "N_HEADS",
    "N_LAYERS",
    "NullSpec",
    "OTHER_TOKEN",
    "S2DatasetBundle",
    "SHIFT_TEMPLATE",
    "SearchSpec",
    "build_s2_dataset_bundle",
    "build_shuffled_pair_dataset_bundle",
    "candidate_table_rows",
    "generate_training_latents",
    "run_candidate_like_null_search",
    "run_random_site_null_search",
    "shuffled_pair_is_available",
    "split_manifest_records",
]
